name: Release Flow
on:
  release:
    types: [published]
jobs:
  publish-image:
    name: Publish Docker image
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build version tagged images
        run: |
          IMAGE_NAME=$(basename $GITHUB_REPOSITORY)
          docker build -t ${{secrets.DOCKER_USER}}/$IMAGE_NAME:${{ github.event.release.tag_name }} . --push
